from selenium.webdriver import Chrome, ChromeOptions
from webdriver_manager.chrome import ChromeDriverManager

DEFAULT_WEBDRIVER_LARGE_DELAY = 1
DEFAULT_WEBDRIVER_DELAY = DEFAULT_WEBDRIVER_LARGE_DELAY * .2
DEFAULT_WEBDRIVER_DELAY_FRACTION = DEFAULT_WEBDRIVER_DELAY / 50

BOWSER_CLASS = Chrome
BROWSER_OPTIONS_CLASS = ChromeOptions
BROWSER_MANAGER_CLASS = ChromeDriverManager

DEFAULT_BROWSER_BOTTING_VALUE = False
DEFAULT_BOOTED_VALUE = False
