print-status: False

api:
    server:
        scheme: http
        port: 5100
    security:
        secret: ${SECURITY_KEY:local-secret-key}
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

whats-app:
    web:
        authentication:
            time-out-in-seconds: 60

swagger:
    host: localhost:${api.server.port}
