print-status: False

api:
    server:
        scheme: http
        port: 5100
        host: localhost
    security:
        secret: ${SECURITY_KEY:local-secret-key}
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

swagger:
    host: ${api.server.host}:${api.server.port}
