print-status: False
api:
    name: IdealizarWhatsAppWebApi
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    security:
        secret: default
    server:
        scheme: https
        host: 0.0.0.0
        port: 5100
        base-url: /idealizar-whats-app-web-api

whats-app:
    web:
        base-url: "https://web.whatsapp.com/"
        authentication:
            time-out: ${WHATS_APP_WEB_AUTHENTICATION_TIME_OUT:180}
            pre-delay: 1
            screenshot-time-renew: 15
        browser:
            hidden: True
    manager:
        base-url: 'http://192.168.25.3:5500/idealizar-whats-app-manager-api'

swagger:
    host: ${api.server.host}:${api.server.port}${api.server.base-url}
    schemes: [${api.server.scheme}]
    info:
        title: {api.name}
        version: 0.0.1
        description: Idealizar Pooler Api
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
